version: '3.8'
services:
  tourniquet.postgre:
    container_name: postgreSql
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=Password12
      - POSTGRES_DB=TurnstileDb
  tourniquet.redis:
    container_name: some-redis
    restart: always
    ports:
      - "6379:6379"
  tourniquet.api:
    container_name: web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings: PostgreSql=User ID=sa; Password=Password12; Server=tourniquet.postgre; Port=5432;Database=TurnstileDb;Integrated Security=true;Pooling=true"
      - RedisSettings:Port=6379
      - RedisSettings:Host=tourniquet.redis
    ports:
      - "5001:80"
    depends_on:
      - tourniquet.postgre
      - tourniquet.redis